services:
  CameraCaptureBot:
    image: camera_capture_bot:test
    container_name: camera-capture-bot
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./Images/:/app/Images/
    configs:
      - source: appsettings
        target: /app/appsettings.json
    restart: unless-stopped

configs:
  appsettings:
    file: ./CameraCaptureBot.Core/appsettings.json
