services:
  CameraCaptureBot:
    image: registry.cn-beijing.aliyuncs.com/nidb-cr/camera-capture-bot:v8.1.2.3
    container_name: camera-capture-bot
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./IsolatedStorage/:/root/.local/share/IsolatedStorage/
    configs:
      - source: appsettings
        target: /app/appsettings.json
    restart: unless-stopped

configs:
  appsettings:
    file: ./CameraCaptureBot.Core/appsettings.json
