name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Aliyun
        uses: docker/login-action@v3
        with:
          registry: "registry.cn-beijing.aliyuncs.com"
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: registry.cn-beijing.aliyuncs.com/nidb-cr/streaming-capture-bot:git
          provenance: true
          sbom: true
          platforms: linux/amd64,windows/amd64
